version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - apt-get update -y
      - apt-get install -y wget unzip
      - chmod +x ./library_back/gradlew
      - ./library_back/gradlew --version
  pre_build:
    commands:
      - cd ./library_front
      - npm install
      - cd ..
      - ./library_back/gradlew clean
  build:
    commands:
      - cd ./library_front
      - npm run build
      - cd ..
      - cd ./library_back
      - ./gradlew build
      - echo "Build completed."

artifacts:
  files:
    - library_front/dist/**/*
    - library_back/build/libs/*.jar
