version: 0.2
phases:
  install:
    commands:
      - echo "=== Installing Dependencies ==="
      - node -v
      - npm -v
      - rm -rf node_modules
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo "=== Cleaning Previous Artifacts & Vite Cache ==="
      - rm -rf dist
      - rm -rf node_modules/.vite
      - git fetch --all
      - git reset --hard origin/main

  build:
    commands:
      - echo "=== Running Build ==="
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist   

cache:
  paths: []  
