version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
      - rm -rf node_modules
      - cd ./librarysystem_front
      - npm install
  pre_build:
    commands:
      - echo "=== Clean previous build artifacts ==="
      - rm -rf dist
      - rm -rf node_modules/.vite

  build:
    commands:
      - echo "=== Run build ==="
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths: []
