version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - cd ./librarysystem_front
      - echo "install global dependencies if needed"
      - npm install -g npm@9
      - yum update -y
  pre_build:
    commands:
      - echo "install project dependencies"
      - npm install
      - cd ..
      - echo "Checking library-backend directory..."
      - if [ ! -d "./library-backend" ]; then echo "Directory library-backend not found"; exit 1; fi
      - chmod +rx ./library-backend               # 디렉토리 접근 권한
      - chmod +x ./library-backend/gradlew        # gradlew 실행 권한 부여
      - ls -l ./library-backend/gradlew           # 권한 확인
  build:
    commands:
      - cd ./librarysystem_front
      - npm run build
      - cd ../library-backend
      - echo "Current directory: $(pwd)"
      - ./gradlew clean build  
      - echo "Build completed."
    finally:
      - echo "Finally block executed."

artifacts:
  files:
    - ../librarysystem_front/dist
    - ../library-backend/build/libs/*.jar
