version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "현재 위치 확인:"
      - pwd
      - cd ./librarysystem_front
      - echo "현재 폴더 파일 목록:"
      - ls -al          # 파일이 실제로 존재하는지 로그로 보여줍니다.
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'

