version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - yum update -y
      - cd ./library_front
      - npm install
  pre_build:
    commands:
      - cd ..
      - ./library_back/gradlew clean
      - chmod +rx ./library_back        # 디렉토리 접근 권한
      - chmod +x ./library_back/gradlew # gradlew 실행 권한 부여
      - ls -l ./library_back/gradlew    # 권한 확인
  build:
    commands:
      - cd ./library_front
      - npm run build
      - cd ..
      - cd ./library_back
      - ./gradlew build
      - echo "Build completed."

artifacts:
  files:
    - library_front/dist/**/*
    - library_back/build/libs/*.jar
