version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - cd ./librarysystem_front
      - echo "install global dependencies if needed"
      - npm install -g npm@9
      - ../library-backendgradlew clean
  pre_build:
    commands:
      - echo "install project dependencies"
      - cd ../librarysystem_front
      - npm install
  build:
    commands:
      - npm run build
      - cd ../library-backend
      - ./gradlew build
      - echo "Build completed."
    finally:
      - echo "Finally block executed."

artifacts:
  files:
    - ../librarysystem_front/dist
    - ../library-backend/build/libs/*.jar
