version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 416225317325.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=416225317325.dkr.ecr.us-east-2.amazonaws.com/swban/ai08_05
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - cd librarysystem_front
      - docker build -t $REPOSITORY_URI:latest librarysystem_front
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed! 준비된 파일을 Deploy 단계로 전달합니다.

# ▼ 핵심: 이 설정이 있어야 S3(아티팩트)를 통해 Deploy 단계로 파일이 넘어갑니다.
artifacts:
  files:
    - librarysystem_front/deployment.yml
    - librarysystem_front/service.yml


