version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd ./librarysystem_front
      - echo "install global dependencies if needed"
      - npm install -g npm@9

  pre_build:
    commands:
      - echo "install project dependencies"
      - rm -rf node_modules
      - npm install

  build:
    commands:
      - echo "run React build"
      - npm run build
      - echo "Build completed."
    finally:
      - echo "Finally block executed."

artifacts:
  base-directory: ./librarysystem_front/dist
  files:
    - '**/*'

cache:
  paths: []
