version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd ./librarysystem_front
      - rm -rf node_modules
      - npm install -g npm@9
      - npm install --legacy-peer-deps
  pre_build:
    commands:
      - echo "=== Clean previous build artifacts ==="
      - rm -rf dist
      - rm -rf node_modules/.vite

  build:
    commands:
      - echo "=== Run build ==="
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: librarysystem_front/dist

cache:
  paths: []
